/**
 * Data Type Codes (supplied in a WSTicket).
 * EEW_FORECAST is deprecated by DM-D.S.S; use `DataTypeCode.EEW_EARLY_MOTION_FORECAST` instead.
 */
export enum DataTypeCode {
    EEW_FORECAST = 'VXSE44',
    EEW_EARLY_MOTION_FORECAST = 'VXSE45', // Early Earthquake Warning (early motion forecast)
    EEW_TEST = 'VXSE42',
    EEW_WARNING = 'VXSE43',
    REAL_TIME_SEISMIC_INTENSITY = 'VXSE47',
    EARTHQUAKE_INTENSITY_REPORT = 'VXSE51',
    EARTHQUAKE_INFORMATION_EPICENTER = 'VXSE52',
    EARTHQUAKE_INFORMATION_EPICENTER_INTENSITY = 'VXSE53',
    EARTHQUAKE_INFORMATION_ACTIVITY = 'VXSE56',
    EARTHQUAKE_INFORMATION_COUNT = 'VXSE60',
    EARTHQUAKE_INFORMATION_NOTABLE_UPDATES = 'VXSE61',
    EARTHQUAKE_LONG_MOTION_OBSERVATION = 'VXSE62',
    EARTHQUAKE_DATA_INTENSITY_DISTRIBUTION = 'IXAC41',
    NANKAI_TROUGH_EMERGENCY = 'VYSE50',
    NANKAI_TROUGH_EXPLANATORY_NO_PERIODIC = 'VYSE51',
    NANKAI_TROUGH_EXPLANATORY_REGULAR = 'VYSE52',
    HOKKAIDO_SANRIKU_OFFSHORE_EARTHQUAKE_WARNING = 'VYSE60',
    TSUNAMI_ALERTS = 'VTSE41',
    TSUNAMI_INFORMATION = 'VTSE51',
    TSUNAMI_INFORMATION_OFFSHORE = 'VTSE52',
    TSUNAMI_INTERNATIONAL_DOMESTIC = 'WEPA60',
    EARTHQUAKE_AND_TSUNAMI_INFORMATION = 'VZSE40',
}

/**
 * Classifications as to which services you will be using with the websocket.
 */
export enum Classification {
    TELEGRAM_WEATHER = 'telegram.weather',
    TELEGRAM_EARTHQUAKE = 'telegram.earthquake',
    EEW_WARNING = 'eew.warning',
    EEW_FORECAST = 'eew.forecast',
}